### ISSUE TITLE
table results

### ISSUE THREAD

**Issue by geek-APTX4869** [paolomandica/HALO#1]
Dear author：
  How to choose the configs for different experiments？

**Comment by paolomandica** [comment]
Hi @geek-APTX4869, in the `configs` directory you find config files for each dataset. For example, if you want to train HALO using source+target data (i.e., GTA-V + Cityscapes) you will use the `configs/gtav/source_target.yaml` config file.
Moreover, you can change other hyper-parameters inside the `yaml` file.
Let me know if you need more help.
