### ISSUE TITLE
Negative Curvature Usage

### ISSUE THREAD

**Issue by Bedrettin-Cetinkaya** [paolomandica/HALO#2]
Thanks for this great work and codes. I have a question about mapping Euclidian space to the Poincare ball model. Here, https://github.com/paolomandica/HALO/blob/main/core/utils/hyperbolic.py#L26, you take the negative of the given curvature value and use this negative curvature for mapping to the Poincare space. In contrast, all other previous works in hyperbolic space use positive curvature values. What is the reason for this difference? Is it just a hyperparameter setting?

Thanks in advance.

**Comment by paolomandica** [comment]
Hi @Bedrettin-Cetinkaya, thanks for the question. It all depends on the geoopt manifold class used. If you use [Stereographic](https://geoopt.readthedocs.io/en/stable/manifolds.html#geoopt.manifolds.Stereographic) class like we did, than you set the curvature with a negative value. If instead you decide to use the [PoincareBall](https://geoopt.readthedocs.io/en/stable/manifolds.html#geoopt.manifolds.PoincareBall) class directly, you set the absolute value (i.e. positive) of the curvature and the class itself will convert it to negative where needed. Everything is well detailed on the [official geoopt documentation](https://geoopt.readthedocs.io/en/stable/manifolds.html).

To be even more specific, the `Stereographic` class is the generalization of the various manifolds and can be used to represent both the `PoincareBall`, the `Spherical` and the `Euclidean` ones, depending on the selected curvature. Here is the geoopt description:
```
    Parameters
    ----------
    k : float|tensor
        sectional curvature :math:`\kappa` of the manifold
        - k<0: Poincaré ball (stereographic projection of hyperboloid)
        - k>0: Stereographic projection of sphere
        - k=0: Euclidean geometry
```
